name: rollex_store
description: "Rollex Store App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
